In [5]:
import os
import numpy as np

from ase.poselib.poselib.skeleton.skeleton3d import SkeletonTree
path = "/home/vml/deepmm_ws/ASE/ase/poselib/data/personal/"

# sfu npy file
arm_npy_file = "Armature_tpose.npy"
arm_t_pose = np.load(path + arm_npy_file, allow_pickle=True).item()

In [6]:
print(arm_t_pose.keys())

odict_keys(['rotation', 'root_translation', 'skeleton_tree', 'is_local', '__name__'])


In [7]:
# sfu npy file
print("arm: ", arm_t_pose['rotation']['arr'].shape)
print("arm: ", arm_t_pose['root_translation']['arr'].shape)

arm:  (80, 4)
arm:  (3,)


In [29]:
node = arm_t_pose['skeleton_tree']['node_names']

print(arm_t_pose['skeleton_tree'])

OrderedDict([('node_names', ['Hips', 'Spine', 'Chest', 'UpperChest', 'Neck', 'Head', 'Right_Eye', 'Left_Eye', 'Jaw', 'Neck_Twist_A', 'Left_Shoulder', 'Left_UpperArm', 'Left_LowerArm', 'Left_Hand', 'Left_PinkyProximal', 'Left_PinkyIntermediate', 'Left_PinkyDistal', 'Left_PinkyDistalEnd', 'Left_RingProximal', 'Left_RingIntermediate', 'Left_RingDistal', 'Left_RingDistalEnd', 'Left_MiddleProximal', 'Left_MiddleIntermediate', 'Left_MiddleDistal', 'Left_MiddleDistalEnd', 'Left_IndexProximal', 'Left_IndexIntermediate', 'Left_IndexDistal', 'Left_IndexDistalEnd', 'Left_ThumbProximal', 'Left_ThumbIntermediate', 'Left_ThumbDistal', 'Left_ThumbDistalEnd', 'Left_PinkyProximalDef', 'Left_RingProximalDef', 'Left_MiddleProximalDef', 'Left_IndexProximalDef', 'Left_ThumbIntermediateDef', 'Left_LowerArmEnd', 'Right_Shoulder', 'Right_UpperArm', 'Right_LowerArm', 'Right_Hand', 'Right_PinkyProximal', 'Right_PinkyIntermediate', 'Right_PinkyDistal', 'Right_PinkyDistalEnd', 'Right_RingProximal', 'Right_RingInt

In [25]:
print(arm_t_pose['skeleton_tree']['local_translation']['arr'])

[[ 0.00000000e+00  9.81098633e+01 -1.59045506e+00]
 [ 1.35525272e-20  5.82293844e+00  1.22295462e-01]
 [-1.69406589e-21  1.03404303e+01  0.00000000e+00]
 [-1.69406589e-21  1.03404303e+01  0.00000000e+00]
 [ 1.69406589e-21  2.51046562e+01 -1.53295815e+00]
 [ 0.00000000e+00  1.27474012e+01 -3.55271368e-15]
 [-3.33032942e+00  3.45962811e+00  8.67403030e+00]
 [ 3.33032608e+00  3.45981169e+00  8.67403030e+00]
 [ 0.00000000e+00 -7.63539016e-01  1.28952777e+00]
 [ 0.00000000e+00  6.37370062e+00 -3.55271368e-15]
 [ 9.57135856e-02  1.91492252e+01 -8.72779429e-01]
 [ 1.67435017e+01 -5.68434189e-14 -8.88178420e-16]
 [ 2.84217094e-14  2.85080681e+01 -3.55271368e-15]
 [ 2.41238070e-08  2.40362225e+01 -1.06581410e-14]
 [-4.43684697e-01  7.28817272e+00 -2.93590140e+00]
 [-2.13162821e-14  3.22726226e+00  0.00000000e+00]
 [ 7.10542736e-15  2.02244496e+00 -2.84217094e-14]
 [ 1.42108547e-14  1.85190570e+00  0.00000000e+00]
 [-9.52556968e-01  8.16155338e+00 -1.22424054e+00]
 [-3.19744231e-14  4.36304855e+