In [1]:
import os
import numpy as np
os.getcwd()


'/home/vml/deepmm_ws/ASE'

### Skeleton

In [2]:
from ase.poselib.poselib.skeleton.skeleton3d import SkeletonTree

skeleton_path = "./ase/data/assets/mjcf/amp_humanoid.xml"
t = SkeletonTree.from_mjcf(skeleton_path)

2023-03-07 13:30:31,065 - INFO - logger - logger initialized


Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbx'
FBX tools must be installed from https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_scripting_with_python_fbx_installing_python_fbx_html


In [3]:
t

SkeletonTree(
    node_names=['pelvis', 'torso', 'head', 'right_upper_arm', 'right_lower_arm', 'right_hand', 'left_upper_arm', 'left_lower_arm', 'left_hand', 'right_thigh', 'right_shin', 'right_foot', 'left_thigh', 'left_shin', 'left_foot'],
    parent_indices=tensor([-1,  0,  1,  1,  3,  4,  1,  6,  7,  0,  9, 10,  0, 12, 13]),
    local_translation=tensor([[ 0.0000,  0.0000,  1.0000],
            [ 0.0000,  0.0000,  0.2362],
            [ 0.0000,  0.0000,  0.2239],
            [-0.0240, -0.1831,  0.2435],
            [ 0.0000,  0.0000, -0.2748],
            [ 0.0000,  0.0000, -0.2589],
            [-0.0240,  0.1831,  0.2435],
            [ 0.0000,  0.0000, -0.2748],
            [ 0.0000,  0.0000, -0.2589],
            [ 0.0000, -0.0849,  0.0000],
            [ 0.0000,  0.0000, -0.4215],
            [ 0.0000,  0.0000, -0.4099],
            [ 0.0000,  0.0849,  0.0000],
            [ 0.0000,  0.0000, -0.4215],
            [ 0.0000,  0.0000, -0.4099]])
)

In [5]:
t.local_translation.shape

torch.Size([15, 3])

In [6]:
print(motion['skeleton_tree'].keys())

NameError: name 'motion' is not defined

### Motion Files

In [2]:
import os
import numpy as np
print(os.getcwd())

path = "/home/vml/deepmm_ws/isaac_ws/isaac_example/ASE/ase/data/motions/"
npy_file = "amp_humanoid_walk.npy"
motion = np.load(path + npy_file, allow_pickle=True).item()

print(motion.keys())

/home/vml/deepmm_ws/ASE
odict_keys(['rotation', 'root_translation', 'global_velocity', 'global_angular_velocity', 'skeleton_tree', 'is_local', 'fps', '__name__'])


In [5]:
print('rotation shape: ', motion["rotation"]['arr'].shape)
print('root_translation shape: ', motion["root_translation"]['arr'].shape)
print('global_velocity shape: ', motion["global_velocity"]['arr'].shape)
print('global_angular_velocity shape: ', motion["global_angular_velocity"]['arr'].shape)

root_translation shape:  (40, 3)
rotation shape:  (40, 15, 4)
global_velocity shape:  (40, 15, 3)
global_angular_velocity shape:  (40, 15, 3)


In [4]:
#print("(1, 15, 3), motion global_velocity")
print(motion["root_translation"]['arr'].shape)

(40, 3)
[[ 0.00000e+00 -0.00000e+00  8.54420e-01]
 [ 3.65300e-02 -2.66000e-03  8.50930e-01]
 [ 7.53500e-02 -7.31000e-03  8.48470e-01]
 [ 1.15800e-01 -1.32400e-02  8.47930e-01]
 [ 1.56470e-01 -2.06300e-02  8.50320e-01]
 [ 1.94260e-01 -2.63100e-02  8.53830e-01]
 [ 2.28450e-01 -3.03700e-02  8.57840e-01]
 [ 2.60040e-01 -3.44200e-02  8.62610e-01]
 [ 2.92530e-01 -3.70700e-02  8.67530e-01]
 [ 3.24630e-01 -3.97900e-02  8.72040e-01]
 [ 3.55040e-01 -4.15500e-02  8.75890e-01]
 [ 3.83850e-01 -4.24600e-02  8.78310e-01]
 [ 4.12060e-01 -4.35600e-02  8.79440e-01]
 [ 4.39920e-01 -4.39000e-02  8.79540e-01]
 [ 4.68060e-01 -4.41300e-02  8.78430e-01]
 [ 4.96150e-01 -4.48600e-02  8.76090e-01]
 [ 5.25840e-01 -4.45400e-02  8.72460e-01]
 [ 5.56570e-01 -4.35400e-02  8.68040e-01]
 [ 5.88990e-01 -4.19900e-02  8.63160e-01]
 [ 6.22910e-01 -3.92700e-02  8.58500e-01]
 [ 6.58930e-01 -3.63600e-02  8.54530e-01]
 [ 6.95460e-01 -3.28700e-02  8.51520e-01]
 [ 7.34510e-01 -2.80400e-02  8.49330e-01]
 [ 7.74310e-01 -2.18900e-0

In [29]:
print(motion['skeleton_tree'].keys())

odict_keys(['node_names', 'parent_indices', 'local_translation'])


In [40]:
path = "/home/vml/deepmm_ws/isaac_ws/isaac_example/ASE/ase/data/motions/"
npy_file = "amp_humanoid_walk.npy"
motion = np.load(path + npy_file, allow_pickle=True).item()


output_path = "/home/vml/deepmm_ws/ASE/ase/poselib/data/"
output_npy_file = "concat_humanoid_walk.npy"

def concat_motion(motion, output_path, output_motion):
    path = "/home/vml/deepmm_ws/isaac_ws/isaac_example/ASE/ase/data/motions/"
    npy_file = "amp_humanoid_walk.npy"
    
    concat_motion = motion
    
    num_frame = motion['root_translation']['arr'].shape[0]
    motion_offset = motion["root_translation"]['arr'][-1] - motion["root_translation"]['arr'][0]
    
    next_root_translation = motion_offset + motion["root_translation"]['arr']
    
    new_root_trs = np.append(motion['root_translation']['arr'], next_root_translation, axis=0)
    new_rotation = np.append(motion["rotation"]['arr'], motion["rotation"]['arr'], axis=0)
    new_global_velocity = np.append(motion["global_velocity"]['arr'], motion["global_velocity"]['arr'], axis=0)
    new_global_angular_velocity = np.append(motion["global_angular_velocity"]['arr'], motion["global_angular_velocity"]['arr'], axis=0)
    
    concat_motion['root_translation']['arr'] = new_root_trs
    concat_motion['rotation']['arr'] = new_rotation
    concat_motion['global_velocity']['arr'] = new_global_velocity
    concat_motion['global_angular_velocity']['arr'] = new_global_angular_velocity
    
    #print("new_root_trs.shape: ", concat_motion['root_translation']['arr'].shape)
    #print("new_root_trs.shape: ", concat_motion['rotation']['arr'].shape)
    #print("new_rotation.shape: ", concat_motion['global_velocity']['arr'].shape)
    #print("new_global_velocity.shape: ", concat_motion['global_angular_velocity']['arr'].shape)
    #print("new_global_angular_velocity.shape: ", concat_motion['root_translation']['arr'].shape)
    np.save(output_path + output_npy_file, concat_motion)
    print("saved files in ", output_path +output_npy_file)
    print("motion data length: ", concat_motion['root_translation']['arr'].shape[0])
    return concat_motion

concat_motion = concat_motion(motion, output_path, output_npy_file)
print(concat_motion['fps'])

saved files in  /home/vml/deepmm_ws/ASE/ase/poselib/data/concat_humanoid_walk.npy
motion data length:  80
30.0


In [54]:
path = "/home/vml/deepmm_ws/isaac_ws/isaac_example/ASE/ase/data/motions/"
npy_file = "amp_humanoid_walk.npy"
motion = np.load(path + npy_file, allow_pickle=True).item()


output_path = "/home/vml/deepmm_ws/ASE/ase/poselib/data/"
output_npy_file = "concat_humanoid_walk.npy"

def concat_motion(num, motion, output_path, output_motion):
    path = "/home/vml/deepmm_ws/isaac_ws/isaac_example/ASE/ase/data/motions/"
    npy_file = "amp_humanoid_walk.npy"
    import copy

    concat_motion = copy.deepcopy(motion)
    num_frame = motion['root_translation']['arr'].shape[0]
    motion_offset = motion["root_translation"]['arr'][-1] - motion["root_translation"]['arr'][0]
    
    new_root_trs = copy.deepcopy(motion['root_translation']['arr'])
    new_rotation = copy.deepcopy(motion["rotation"]['arr'])
    new_global_velocity = copy.deepcopy(motion["global_velocity"]['arr'])
    new_global_angular_velocity = copy.deepcopy(motion["global_angular_velocity"]['arr'])
    
    for idx in range(1, num + 1):
        idx_offset = motion_offset * idx
        next_root_translation = idx_offset + motion["root_translation"]['arr']
        new_root_trs = np.append(new_root_trs, next_root_translation, axis=0)
        new_rotation = np.append(new_rotation, motion["rotation"]['arr'], axis=0)
        new_global_velocity = np.append(new_global_velocity, motion["global_velocity"]['arr'], axis=0)
        new_global_angular_velocity = np.append(new_global_angular_velocity, motion["global_angular_velocity"]['arr'], axis=0)
    
        concat_motion['root_translation']['arr'] = new_root_trs
        concat_motion['rotation']['arr'] = new_rotation
        concat_motion['global_velocity']['arr'] = new_global_velocity
        concat_motion['global_angular_velocity']['arr'] = new_global_angular_velocity
        
        #print("*"*10)
        #print("new_root_trs.shape: ", concat_motion['root_translation']['arr'].shape)
        #print("new_root_trs.shape: ", concat_motion['rotation']['arr'].shape)
        #print("new_rotation.shape: ", concat_motion['global_velocity']['arr'].shape)
        #print("new_global_velocity.shape: ", concat_motion['global_angular_velocity']['arr'].shape)
        #print("new_global_angular_velocity.shape: ", concat_motion['root_translation']['arr'].shape)
        #print("*"*10)

        np.save(output_path + output_npy_file, concat_motion)
        
    print("saved files in ", output_path +output_npy_file)
    print("motion data length: ", concat_motion['root_translation']['arr'].shape[0])
    print(num + 1, " times doubled")
    return concat_motion

concat_motion = concat_motion(10, motion, output_path, output_npy_file)


saved files in  /home/vml/deepmm_ws/ASE/ase/poselib/data/concat_humanoid_walk.npy
motion data length:  440
11  times doubled


1
2
3
4
5
6
7
8
9
10


dir(curr_motion)

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_compute_angular_velocity', '_compute_velocity', '_fps', '_get_pairwise_average_translation', '_global_rotation', '_is_local', '_local_rotation', '_remapped_to', '_skeleton_tree', '_to_state_vector', '_transfer_to', 'clone', 'compute_forward_vector', 'crop', 'drop_nodes_by_names', 'fps', 'from_dict', 'from_fbx', 'from_file', 'from_rotation_and_root_translation', 'from_skeleton_state', 'from_state_vector_and_velocity', 'global_angular_velocity', 'global_repr', 'global_root_angular_velocity', 'global_root_rotation', 'global_root_velocity', 'global_root_yaw_rotation', 'global_rotation', 'global_transformation', 'global_translation', 'global_translation_xy', 'global_translation_xz', 'global_velocity', 'invariant_property', 'is_local', 'keep_nodes_by_names', 'local_repr', 'local_rotation', 'local_rotation_to_root', 'local_transformation', 'local_translation', 'local_translation_to_root', 'num_joints', 'retarget_to', 'retarget_to_by_tpose', 'root_translation', 'root_translation_xy', 'rotation', 'skeleton_tree', 'tensor', 'time_delta', 'to_dict', 'to_file', 'zero_pose']


In [9]:
import os
import numpy as np
print(os.getcwd())

path = "/home/vml/deepmm_ws/ASE/ase/poselib/data/"
npy_file = "ybot_walking.npy"
motion = np.load(path + npy_file, allow_pickle=True).item()

print(motion.keys())

/home/vml/deepmm_ws/ASE
odict_keys(['rotation', 'root_translation', 'global_velocity', 'global_angular_velocity', 'skeleton_tree', 'is_local', 'fps', '__name__'])


In [10]:
print('root_translation shape: ', motion["root_translation"]['arr'].shape)
print('rotation shape: ', motion["rotation"]['arr'].shape)
print('global_velocity shape: ', motion["global_velocity"]['arr'].shape)
print('global_angular_velocity shape: ', motion["global_angular_velocity"]['arr'].shape)

root_translation shape:  (58, 3)
rotation shape:  (58, 65, 4)
global_velocity shape:  (58, 65, 3)
global_angular_velocity shape:  (58, 65, 3)


In [11]:
print(motion['skeleton_tree'])
'''
OrderedDict([('node_names', ['mixamorig:Hips', 
'mixamorig:Spine', 'mixamorig:Spine1', 'mixamorig:Spine2', 
'mixamorig:Neck', 'mixamorig:Head', 'mixamorig:HeadTop_End', 
'mixamorig:RightShoulder', 'mixamorig:RightArm', 'mixamorig:RightForeArm', 
'mixamorig:RightHand', 'mixamorig:RightHandThumb1', 'mixamorig:RightHandThumb2', 'mixamorig:RightHandThumb3', 'mixamorig:RightHandThumb4', 'mixamorig:RightHandIndex1', 'mixamorig:RightHandIndex2', 'mixamorig:RightHandIndex3', 'mixamorig:RightHandIndex4', 
'mixamorig:RightHandMiddle1', 'mixamorig:RightHandMiddle2', 'mixamorig:RightHandMiddle3', 'mixamorig:RightHandMiddle4', 'mixamorig:RightHandRing1', 'mixamorig:RightHandRing2', 'mixamorig:RightHandRing3', 'mixamorig:RightHandRing4', 'mixamorig:RightHandPinky1', 'mixamorig:RightHandPinky2', 'mixamorig:RightHandPinky3', 'mixamorig:RightHandPinky4', 
'mixamorig:LeftShoulder', 'mixamorig:LeftArm', 'mixamorig:LeftForeArm', 
'mixamorig:LeftHand', 'mixamorig:LeftHandThumb1', 'mixamorig:LeftHandThumb2', 'mixamorig:LeftHandThumb3', 'mixamorig:LeftHandThumb4', 'mixamorig:LeftHandIndex1', 'mixamorig:LeftHandIndex2', 'mixamorig:LeftHandIndex3', 'mixamorig:LeftHandIndex4', 'mixamorig:LeftHandMiddle1', 'mixamorig:LeftHandMiddle2', 'mixamorig:LeftHandMiddle3', 'mixamorig:LeftHandMiddle4', 'mixamorig:LeftHandRing1', 'mixamorig:LeftHandRing2', 'mixamorig:LeftHandRing3', 'mixamorig:LeftHandRing4', 'mixamorig:LeftHandPinky1', 'mixamorig:LeftHandPinky2', 'mixamorig:LeftHandPinky3', 'mixamorig:LeftHandPinky4', 
'mixamorig:RightUpLeg', 'mixamorig:RightLeg', 'mixamorig:RightFoot', 'mixamorig:RightToeBase', 'mixamorig:RightToe_End', 
'mixamorig:LeftUpLeg', 'mixamorig:LeftLeg', 'mixamorig:LeftFoot', 'mixamorig:LeftToeBase', 'mixamorig:LeftToe_End'])
'''

OrderedDict([('node_names', ['mixamorig:Hips', 'mixamorig:Spine', 'mixamorig:Spine1', 'mixamorig:Spine2', 'mixamorig:Neck', 'mixamorig:Head', 'mixamorig:HeadTop_End', 'mixamorig:RightShoulder', 'mixamorig:RightArm', 'mixamorig:RightForeArm', 'mixamorig:RightHand', 'mixamorig:RightHandThumb1', 'mixamorig:RightHandThumb2', 'mixamorig:RightHandThumb3', 'mixamorig:RightHandThumb4', 'mixamorig:RightHandIndex1', 'mixamorig:RightHandIndex2', 'mixamorig:RightHandIndex3', 'mixamorig:RightHandIndex4', 'mixamorig:RightHandMiddle1', 'mixamorig:RightHandMiddle2', 'mixamorig:RightHandMiddle3', 'mixamorig:RightHandMiddle4', 'mixamorig:RightHandRing1', 'mixamorig:RightHandRing2', 'mixamorig:RightHandRing3', 'mixamorig:RightHandRing4', 'mixamorig:RightHandPinky1', 'mixamorig:RightHandPinky2', 'mixamorig:RightHandPinky3', 'mixamorig:RightHandPinky4', 'mixamorig:LeftShoulder', 'mixamorig:LeftArm', 'mixamorig:LeftForeArm', 'mixamorig:LeftHand', 'mixamorig:LeftHandThumb1', 'mixamorig:LeftHandThumb2', 'mixa